"use client";

import { type ReactElement } from "react";

import { useConsole } from "@/components/ConsoleProvider";
import { useAsyncAction } from "@/hooks/use-async-action";
import { fetchAdvice, type AdvisorResponse, type ApiError } from "@/lib/client";
import { getZone } from "@/lib/venue";

/**
 * Message for a failed advice request.
 *
 * `AI_UNAVAILABLE` is called out by name because it is not a fault the operator
 * can retry away — it means the deployment has no model key — and saying so is
 * the only honest option. Inventing plausible actions to fill the panel would
 * put unattributed text in front of someone making crowd-safety decisions.
 */
function adviceErrorMessage(error: ApiError): string {
	if (error.code === "AI_UNAVAILABLE") {
		return "AI advisor unavailable — GEMINI_API_KEY not configured on the server. No recommendations can be generated; the zone readings above are unaffected.";
	}
	return error.message;
}

/**
 * AI decision support for the duty manager.
 *
 * Sends the operator's current focus zone (if any) to `POST /api/advisor`,
 * which grounds a Gemini prompt in the same snapshot the map is drawing, and
 * renders the returned actions verbatim. Nothing in this panel is generated
 * client-side: if the model does not answer, the panel says why.
 */
export function OpsAdvisor(): ReactElement {
	const { selectedZoneId } = useConsole();
	const { state, run } = useAsyncAction<AdvisorResponse>();

	const focusZone = selectedZoneId === null ? undefined : getZone(selectedZoneId);
	const busy = state.status === "loading";

	return (
		<div className="advisor">
			<div className="advisor__controls">
				<button
					type="button"
					className="button button--primary"
					onClick={(): void => {
						run((signal) => fetchAdvice(selectedZoneId, signal));
					}}
					disabled={busy}
				>
					{busy ? "Consulting the model…" : "Get AI recommendations"}
				</button>
				<p className="advisor__focus">
					{focusZone === undefined
						? "Advising across the whole venue. Select a zone on the map to weight the advice towards it."
						: `Advice will be weighted towards ${focusZone.name}.`}
				</p>
			</div>

			<div className="result" aria-busy={busy} aria-live="polite">
				{state.status === "loading" && <p className="result__pending">Generating prioritised actions…</p>}

				{state.status === "error" && (
					<p className="notice notice--error" role="alert">
						{adviceErrorMessage(state.error)}
					</p>
				)}

				{state.status === "ok" && (
					<>
						<p className="model-output">{state.data.actions}</p>
						<p className="attribution">
							Generated by Google {state.data.model} from the snapshot at Fan Friction Score{" "}
							{state.data.snapshot.frictionScore}/100.
							{state.data.snapshot.criticalZones.length > 0
								? ` Critical zones at that instant: ${state.data.snapshot.criticalZones.join(", ")}.`
								: " No zones were critical at that instant."}
						</p>
					</>
				)}
			</div>
		</div>
	);
}
